### ISSUE TITLE
Add CFLAG arguments while installing ngic-rtc for KNI and Static_Arp

### ISSUE THREAD

**Issue by Sandeep-Sarma** [omec-project/omec-project-ci#11]
To avoid configuration backup of makefiles in ngic-rtc cp/dp to interchange between STATIC_ARP and KNI tests. These options can be added as CFLAGS during the installation of ngic-rtc.

`https://github.com/omec-project/omec-project-ci/blob/master/Jenkinsfile-omec-install-ngic-rtc-vnf.groovy`

`cp -f ${install_path}/wo-config/kni_Makefile ${install_path}/ngic-rtc/dp/Makefile`

**Comment by krsna1729** [comment]
The option I was talking about was leveraging EXTRA_CFLAGS wherever possible instead of overwriting Makefiles
https://github.com/omec-project/ngic-rtc/pull/15/files#diff-3254677a7917c6c01f55212f86c57fbfR21

There is also a PR open to allow placing .mk files in CP and DP directories for customization without overwriting or editing the base Makefiles

https://github.com/omec-project/ngic-rtc/pull/18/files
If that solves the problem, we should prioritize the PR.

/cc @somnathchakrabarti @suresh-marikkannu

**Comment by micpez** [comment]
Solution does not seem to work.

**Comment by krsna1729** [comment]
@micpez then we should try the second option listed above which allows to place customization makefiles as .mk in CP and DP.

Also for CI to go back to working state shall i revert the commit?

**Comment by micpez** [comment]
> Also for CI to go back to working state shall i revert the commit?
Yes, better, otherwise tests will not pass.

**Comment by krsna1729** [comment]
@micpez i should have looked at the PR better. The below would have been enough. No need to undefine, since they are not defined by default.

TC1
```
ssh ngic-cp1 'cd ${basedir_cp1}/ngic-rtc/cp && source ../setenv.sh && make clean && make EXTRA_CFLAGS=-DZMQ_COMM'
ssh ngic-dp1 'cd ${basedir_dp1}/ngic-rtc/dp && source ../setenv.sh && make clean && make EXTRA_CFLAGS="-DZMQ_COMM"'
```

TC2
```
cd ${basedir_dp1}/ngic-rtc/dp && source ../setenv.sh && make clean && make EXTRA_CFLAGS="-DSTATIC_ARP"
```

**Comment by micpez** [comment]
> @micpez i should have looked at the PR better. The below would have been enough. No need to undefine, since they are not defined by default.
 
@sai, my only concern is if it is intended that ZMQ_COMM is not the default.
Looking at the comment here, it seems ambiguous to me.
https://github.com/omec-project/ngic-rtc/blob/ab1b38fd7d1cd857e5f6276baffc7037c45fc5a8/config/ng-core_cfg.mk#L4-L6

@suresh-marikkannu, is the comment intentional `#CFLAGS += -DZMQ_COMM`?
